"""
Healer Agent.

Diagnoses test failures and classifies them into LOCATOR_DRIFT, REAL_BUG, or ENVIRONMENT_FLAKE.
Generates proposed locator fixes with diffs and confidence scores, enforcing human ratification
gate before healing hardens into the repository (Awesome Testing 2026 pattern).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional

from src.agents.base_agent import BaseAgent, AgentResponse, AgentRole
from src.mcp_gateway.tool_registry import MCPToolRegistry

logger = logging.getLogger("BankAI.HealerAgent")


class FailureClassification(str, Enum):
    LOCATOR_DRIFT = "LOCATOR_DRIFT"       # UI DOM updated, functional behavior identical
    REAL_BUG = "REAL_BUG"                 # Business logic / assertion mismatch / ledger error
    ENVIRONMENT_FLAKE = "ENVIRONMENT_FLAKE" # Network timeout, 503 Service Unavailable, non-prod restart


@dataclass
class HealingProposal:
    """Proposal generated by Healer Agent for human ratification."""
    step_id: str
    original_locator: str
    proposed_locator: str
    confidence_score: float  # 0.0 to 1.0
    diff_patch: str
    classification: FailureClassification
    auto_apply_eligible: bool  # True only if LOCATOR_DRIFT & confidence >= 0.85


class HealerAgent(BaseAgent):
    """
    Healer Agent responsible for failure classification, self-healing proposal generation,
    and confidence assessment.
    """

    def __init__(self, agent_id: str = "healer-01", tool_registry: Optional[MCPToolRegistry] = None):
        super().__init__(
            agent_id=agent_id,
            name="Self-Healing Diagnosis Agent",
            role=AgentRole.HEALER,
            tool_registry=tool_registry,
            token_budget=10000
        )
        self.confidence_threshold = 0.85

    def process(self, input_data: Dict[str, Any], context: Dict[str, Any]) -> AgentResponse:
        """
        Diagnoses a step failure using error traces, DOM snapshots, and accessibility tree logs.
        """
        failed_step_id = input_data.get("step_id", "UNKNOWN")
        error_log = input_data.get("error_log", "")
        original_locator = input_data.get("locator", "getByRole('button', name='Submit Wire Transfer')")
        dom_snapshot = input_data.get("dom_snapshot", "")

        logger.info(f"[{self.agent_id}] Diagnosing failure for step '{failed_step_id}'")

        classification, proposal = self._diagnose_failure(failed_step_id, original_locator, error_log, dom_snapshot)

        return self.create_response(
            success=True,
            content=f"Failure classified as {classification.value}. Confidence: {proposal.confidence_score:.2f}",
            data={
                "step_id": failed_step_id,
                "classification": classification.value,
                "confidence_score": proposal.confidence_score,
                "original_locator": proposal.original_locator,
                "proposed_locator": proposal.proposed_locator,
                "diff_patch": proposal.diff_patch,
                "auto_apply_eligible": proposal.auto_apply_eligible,
                "requires_human_review": not proposal.auto_apply_eligible or classification == FailureClassification.REAL_BUG
            },
            tokens_used=310
        )

    def _diagnose_failure(
        self, step_id: str, original_locator: str, error_log: str, dom_snapshot: str
    ) -> tuple[FailureClassification, HealingProposal]:
        """Classify root cause and generate proposal."""

        # Case 1: Business assertion failure or DB double-entry mismatch -> REAL_BUG
        if "AssertionError" in error_log or "double_entry" in error_log or "400 Bad Request" in error_log:
            classification = FailureClassification.REAL_BUG
            proposal = HealingProposal(
                step_id=step_id,
                original_locator=original_locator,
                proposed_locator=original_locator,  # No locator change for real bugs
                confidence_score=0.95,
                diff_patch="",
                classification=classification,
                auto_apply_eligible=False
            )
            return classification, proposal

        # Case 2: Network timeout / connection refused -> ENVIRONMENT_FLAKE
        elif "TimeoutError" in error_log or "ECONNREFUSED" in error_log or "503 Service Unavailable" in error_log:
            classification = FailureClassification.ENVIRONMENT_FLAKE
            proposal = HealingProposal(
                step_id=step_id,
                original_locator=original_locator,
                proposed_locator=original_locator,
                confidence_score=0.90,
                diff_patch="",
                classification=classification,
                auto_apply_eligible=False
            )
            return classification, proposal

        # Case 3: Element not found or locator changed -> LOCATOR_DRIFT
        else:
            classification = FailureClassification.LOCATOR_DRIFT
            # Example healing recommendation (converting CSS/old name to modern ARIA locator)
            new_locator = "getByRole('button', name='Confirm & Send Wire Transfer')"
            diff_patch = (
                f"--- a/tests/payment_flow.spec.ts\n"
                f"+++ b/tests/payment_flow.spec.ts\n"
                f"- page.{original_locator}\n"
                f"+ page.{new_locator}\n"
            )
            proposal = HealingProposal(
                step_id=step_id,
                original_locator=original_locator,
                proposed_locator=new_locator,
                confidence_score=0.88,
                diff_patch=diff_patch,
                classification=classification,
                auto_apply_eligible=True
            )
            return classification, proposal
