"""
Planner Agent.

Decomposes complex banking business journeys (e.g., cross-border payment with FX,
compliance hold, account reconciliation) into executable test step graphs.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from src.agents.base_agent import BaseAgent, AgentResponse, AgentRole
from src.mcp_gateway.tool_registry import MCPToolRegistry

logger = logging.getLogger("BankAI.PlannerAgent")


@dataclass
class TestStep:
    """Individual test step within a planned test suite graph."""
    step_id: str
    description: str
    surface: str  # "WEB", "MOBILE", "API", "DB", "ISO20022"
    action: str
    target: str
    payload: Dict[str, Any] = field(default_factory=dict)
    expected_outcome: str = ""
    compliance_tag: Optional[str] = None  # e.g., "SOX-404", "PCI-DSS-3.2", "PSD2-SCA", "SWIFT-2026"


@dataclass
class TestPlan:
    """Decomposed test execution plan generated by Planner Agent."""
    plan_id: str
    title: str
    business_requirement: str
    steps: List[TestStep] = field(default_factory=list)
    risk_level: str = "MEDIUM"  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    estimated_duration_sec: int = 60


class PlannerAgent(BaseAgent):
    """
    Planner Agent responsible for test decomposition, requirement analysis,
    and generating deterministic test execution paths.
    """

    def __init__(self, agent_id: str = "planner-01", tool_registry: Optional[MCPToolRegistry] = None):
        super().__init__(
            agent_id=agent_id,
            name="Test Plan Architect",
            role=AgentRole.PLANNER,
            tool_registry=tool_registry,
            token_budget=15000
        )

    def process(self, input_data: Dict[str, Any], context: Dict[str, Any]) -> AgentResponse:
        """
        Processes a business journey specification and outputs a structured TestPlan.
        """
        user_prompt = input_data.get("requirement", "")
        journey_type = input_data.get("journey_type", "CROSS_BORDER_PAYMENT")

        logger.info(f"[{self.agent_id}] Planning test graph for journey: '{journey_type}'")

        # Decompose requirement into structured steps
        steps = self._decompose_journey(journey_type, user_prompt)
        plan = TestPlan(
            plan_id=f"PLAN-{journey_type}-2026",
            title=f"Automated Test Plan for {journey_type}",
            business_requirement=user_prompt or f"Validate E2E process for {journey_type}",
            steps=steps,
            risk_level="HIGH" if "CROSS_BORDER" in journey_type or "ISO20022" in journey_type else "MEDIUM"
        )

        return self.create_response(
            success=True,
            content=f"Decomposed journey into {len(steps)} executable test steps.",
            data={
                "plan_id": plan.plan_id,
                "title": plan.title,
                "risk_level": plan.risk_level,
                "step_count": len(steps),
                "steps": [
                    {
                        "step_id": s.step_id,
                        "description": s.description,
                        "surface": s.surface,
                        "action": s.action,
                        "target": s.target,
                        "compliance_tag": s.compliance_tag
                    }
                    for s in steps
                ]
            },
            tokens_used=450
        )

    def _decompose_journey(self, journey_type: str, custom_prompt: str) -> List[TestStep]:
        """Decompose banking journey into multi-surface steps."""
        if journey_type == "CROSS_BORDER_PAYMENT":
            return [
                TestStep(
                    step_id="STEP-01",
                    description="Navigate to Corporate Online Banking Portal",
                    surface="WEB",
                    action="navigate",
                    target="https://banking.corp.example.com/login",
                    compliance_tag="PSD2-SCA"
                ),
                TestStep(
                    step_id="STEP-02",
                    description="Authenticate with 2FA token (Persona: Corporate Treasurer)",
                    surface="WEB",
                    action="fill",
                    target="getByRole('textbox', name='Security Token')",
                    compliance_tag="PSD2-SCA"
                ),
                TestStep(
                    step_id="STEP-03",
                    description="Initiate Cross-Border SWIFT Wire Transfer",
                    surface="WEB",
                    action="click",
                    target="getByRole('button', name='Initiate International Wire')"
                ),
                TestStep(
                    step_id="STEP-04",
                    description="Validate generated ISO 20022 pacs.008 message payload",
                    surface="ISO20022",
                    action="validate_xml",
                    target="pacs.008.001.10",
                    compliance_tag="SWIFT-2026"
                ),
                TestStep(
                    step_id="STEP-05",
                    description="Execute payment initiation via Core Banking REST API",
                    surface="API",
                    action="POST",
                    target="/api/v1/payments/swift/initiate"
                ),
                TestStep(
                    step_id="STEP-06",
                    description="Verify double-entry ledger debit and credit reconciliation",
                    surface="DB",
                    action="verify_double_entry",
                    target="ledger_entries",
                    compliance_tag="SOX-404"
                )
            ]
        else:
            return [
                TestStep(
                    step_id="STEP-01",
                    description="Execute default balance enquiry step",
                    surface="API",
                    action="GET",
                    target="/api/v1/accounts/balance"
                )
            ]
